### ISSUE TITLE
Parsing cert file hard for windows users

### ISSUE THREAD

**Issue by gizmocuz** [cesanta/ssl_wrapper#3]
Parsing a certificate with the HTTPS example is hard for windows
for instance the certificate is on E:\cert.pem

ssl://443:E:\server_cert.pem 127.0.0.1:1570

internally it sets the cert to "E"

Small typo in the example:

shedule closing 

should be

schedule closing

Thanks for this great lib !

**Comment by cpq** [comment]
Thanks, typo fixed!

**Comment by gizmocuz** [comment]
Thanks, did you had a change to look at the windows certificate problem?
