### ISSUE TITLE
Chrome reports obsolete cryptography

### ISSUE THREAD

**Issue by davidsblog** [cesanta/ssl_wrapper#4]
I have used `/net_skeleton/scripts/generate_ssl_certificates.sh` to create a certificate and then used this with *ssl_wrapper*.  It works fine, but Chrome reports that the connection uses obsolete cryptography.

Is it possible to configure for what Chrome considers "modern cryptography"?  Can that be done?

**Comment by cpq** [comment]
Try to add `-sha256` option to openssl x509 command

**Comment by davidsblog** [comment]
Thanks, good suggestion.  I have tried that and it hasn't prevented Chrome from complaining.  I think that Chrome is possibly complaining about RSA being used as the key exchange mechanism.

I have an instance of Apache running with self signed certs which Chrome says  has "modern cryptography" ... so perhaps I take the certs generated from `generate_ssl_certificates.sh` (with your `-sha256` option added) and see if they work on that server.  That may help me to figure out if the cert is at fault or if it's something in the code of *net_skeleton*.  Thanks again for your advice...

**Comment by davidsblog** [comment]
OK, I think it must be something in the code of *net_skeleton*.  I have created new a brand new certificate using the modified `generate_ssl_certificates.sh` (with `-sha256` added).  I have use this certificate in *ssl_wrapper* and Chrome reports this:

![wrapper](https://cloud.githubusercontent.com/assets/6596121/8081573/d8bd1be0-0f6d-11e5-8189-85fbd2192253.png)

Then I used the same certificate in Apache on the same box and Chrome reports this:

![apache](https://cloud.githubusercontent.com/assets/6596121/8081599/f6a5c3aa-0f6d-11e5-93b6-894c6d7468a4.png)

So I am thinking something would need to be added to the openssl ciphers configuration in `net_skeleton.c` to make Chrome consider it to be "modern cryptography"?

Please let me know if you have any suggestions...

**Comment by cpq** [comment]
@roger, could you take a quick look at this please?

**Comment by davidsblog** [comment]
Wow, thanks guys! Cheers.
